model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
data_format: chat
mask_prompt: true

train_type: lora
epochs: 1
batch_size: 16        
micro_batch_size: 1
learning_rate: 2.0e-4
max_seq_length: 256   
weight_decay: 0.0
iters: 200

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - o_proj

save_path: ./out/tinyllama-customer-support
log_interval: 10
eval_interval: 50  
save_interval: 50